name: google_maps_example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.2
  location: ^8.0.0
  flutter_bloc: ^9.1.1
  flutter_typeahead: ^5.2.0
  flutter_google_places_sdk: ^0.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gym.png
    - assets/store.png
